FROM bcm-registry:30000/tomcat:7-jre7-nio-apm
COPY target/ordercenter.war /usr/local/tomcat/webapps/
RUN mv /usr/local/tomcat/webapps/ordercenter.war /usr/local/tomcat/webapps/ordercenter-newwsctest.war
CMD ["catalina.sh", "run"]


