package com.bonc.busi.ftp;

import java.io.Serializable;

public class RemoteServerInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.id
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.operator_id
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String operator_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.remote_server_name
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String remote_server_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.ip_address
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String ip_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.port
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private Short port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.account
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.password
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.file_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String file_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.local_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String local_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.upload_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String upload_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.local_upload_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String local_upload_path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column remote_server_info.local_bak_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    private String local_bak_path;
    
    //added by shenyj for download order file
    private String order_file;
    private String local_store_path;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.id
     *
     * @return the value of remote_server_info.id
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.id
     *
     * @param id the value for remote_server_info.id
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.operator_id
     *
     * @return the value of remote_server_info.operator_id
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getOperator_id() {
        return operator_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.operator_id
     *
     * @param operator_id the value for remote_server_info.operator_id
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setOperator_id(String operator_id) {
        this.operator_id = operator_id == null ? null : operator_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.remote_server_name
     *
     * @return the value of remote_server_info.remote_server_name
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getRemote_server_name() {
        return remote_server_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.remote_server_name
     *
     * @param remote_server_name the value for remote_server_info.remote_server_name
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setRemote_server_name(String remote_server_name) {
        this.remote_server_name = remote_server_name == null ? null : remote_server_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.ip_address
     *
     * @return the value of remote_server_info.ip_address
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getIp_address() {
        return ip_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.ip_address
     *
     * @param ip_address the value for remote_server_info.ip_address
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setIp_address(String ip_address) {
        this.ip_address = ip_address == null ? null : ip_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.port
     *
     * @return the value of remote_server_info.port
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public Short getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.port
     *
     * @param port the value for remote_server_info.port
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setPort(Short port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.account
     *
     * @return the value of remote_server_info.account
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.account
     *
     * @param account the value for remote_server_info.account
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.password
     *
     * @return the value of remote_server_info.password
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.password
     *
     * @param password the value for remote_server_info.password
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.file_path
     *
     * @return the value of remote_server_info.file_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getFile_path() {
        return file_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.file_path
     *
     * @param file_path the value for remote_server_info.file_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setFile_path(String file_path) {
        this.file_path = file_path == null ? null : file_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.local_path
     *
     * @return the value of remote_server_info.local_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getLocal_path() {
        return local_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.local_path
     *
     * @param local_path the value for remote_server_info.local_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setLocal_path(String local_path) {
        this.local_path = local_path == null ? null : local_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.upload_path
     *
     * @return the value of remote_server_info.upload_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getUpload_path() {
        return upload_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.upload_path
     *
     * @param upload_path the value for remote_server_info.upload_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setUpload_path(String upload_path) {
        this.upload_path = upload_path == null ? null : upload_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.local_upload_path
     *
     * @return the value of remote_server_info.local_upload_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getLocal_upload_path() {
        return local_upload_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.local_upload_path
     *
     * @param local_upload_path the value for remote_server_info.local_upload_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setLocal_upload_path(String local_upload_path) {
        this.local_upload_path = local_upload_path == null ? null : local_upload_path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column remote_server_info.local_bak_path
     *
     * @return the value of remote_server_info.local_bak_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public String getLocal_bak_path() {
        return local_bak_path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column remote_server_info.local_bak_path
     *
     * @param local_bak_path the value for remote_server_info.local_bak_path
     *
     * @mbggenerated Thu Feb 04 13:46:05 CST 2016
     */
    public void setLocal_bak_path(String local_bak_path) {
        this.local_bak_path = local_bak_path == null ? null : local_bak_path.trim();
    }
    
    /**
     * For download order file from xcloud
     * @author yanjunshen
     * 
     */
    public  String getOrder_file() {
    	return order_file;
    }
    public void setOrder_file(String fname) {
    	this.order_file = fname;
    }
    //local_store_path
    public  String getLocal_store_path() {
    	return local_store_path;
    }
    public void setLocal_store_path(String path) {
    	this.local_store_path = path;
    }
 
}