FROM bcm-registry:30000/tomcat:7-jre7-ths
COPY target/ordertask-scheduled2.war /usr/local/tomcat/webapps/
RUN mv /usr/local/tomcat/webapps/ordertask-scheduled2.war /usr/local/tomcat/webapps/cordertask-sche2.war
CMD ["catalina.sh", "run"]

