FROM bcm-registry:30000/tomcat:7-jre7-apm
COPY target/ordertask-service.war /usr/local/tomcat/webapps/
RUN mv /usr/local/tomcat/webapps/ordertask-service.war /usr/local/tomcat/webapps/xordertask-service-yw.war

