package com.bonc.busi.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class OrderControlLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CONTROL_LOG.ID
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CONTROL_LOG.CONTROL_CODE
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    private String CONTROL_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CONTROL_LOG.TENANT_ID
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    private String TENANT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CONTROL_LOG.BUSI_TIME
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    private Date BUSI_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CONTROL_LOG.BUSI_RESULT
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    private String BUSI_RESULT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDER_CONTROL_LOG.BUSI_MESSAGE
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    private String BUSI_MESSAGE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CONTROL_LOG.ID
     *
     * @return the value of ORDER_CONTROL_LOG.ID
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CONTROL_LOG.ID
     *
     * @param ID the value for ORDER_CONTROL_LOG.ID
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CONTROL_LOG.CONTROL_CODE
     *
     * @return the value of ORDER_CONTROL_LOG.CONTROL_CODE
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public String getCONTROL_CODE() {
        return CONTROL_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CONTROL_LOG.CONTROL_CODE
     *
     * @param CONTROL_CODE the value for ORDER_CONTROL_LOG.CONTROL_CODE
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public void setCONTROL_CODE(String CONTROL_CODE) {
        this.CONTROL_CODE = CONTROL_CODE == null ? null : CONTROL_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CONTROL_LOG.TENANT_ID
     *
     * @return the value of ORDER_CONTROL_LOG.TENANT_ID
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public String getTENANT_ID() {
        return TENANT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CONTROL_LOG.TENANT_ID
     *
     * @param TENANT_ID the value for ORDER_CONTROL_LOG.TENANT_ID
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public void setTENANT_ID(String TENANT_ID) {
        this.TENANT_ID = TENANT_ID == null ? null : TENANT_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CONTROL_LOG.BUSI_TIME
     *
     * @return the value of ORDER_CONTROL_LOG.BUSI_TIME
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public Date getBUSI_TIME() {
        return BUSI_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CONTROL_LOG.BUSI_TIME
     *
     * @param BUSI_TIME the value for ORDER_CONTROL_LOG.BUSI_TIME
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public void setBUSI_TIME(Date BUSI_TIME) {
        this.BUSI_TIME = BUSI_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CONTROL_LOG.BUSI_RESULT
     *
     * @return the value of ORDER_CONTROL_LOG.BUSI_RESULT
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public String getBUSI_RESULT() {
        return BUSI_RESULT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CONTROL_LOG.BUSI_RESULT
     *
     * @param BUSI_RESULT the value for ORDER_CONTROL_LOG.BUSI_RESULT
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public void setBUSI_RESULT(String BUSI_RESULT) {
        this.BUSI_RESULT = BUSI_RESULT == null ? null : BUSI_RESULT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDER_CONTROL_LOG.BUSI_MESSAGE
     *
     * @return the value of ORDER_CONTROL_LOG.BUSI_MESSAGE
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public String getBUSI_MESSAGE() {
        return BUSI_MESSAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDER_CONTROL_LOG.BUSI_MESSAGE
     *
     * @param BUSI_MESSAGE the value for ORDER_CONTROL_LOG.BUSI_MESSAGE
     *
     * @mbggenerated Fri Jun 02 11:36:01 CST 2017
     */
    public void setBUSI_MESSAGE(String BUSI_MESSAGE) {
        this.BUSI_MESSAGE = BUSI_MESSAGE == null ? null : BUSI_MESSAGE.trim();
    }
}