package com.bonc.busi.invoke;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IDataSendService", targetNamespace = "http://dataservice.ws.webservice.bonc.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IDataSendService {

	/**
	 * 
	 * @param jsonParam
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String genAndSend(
			@WebParam(name = "jsonParam", partName = "jsonParam") String jsonParam);

	/**
	 * 
	 * @param username
	 * @param password
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String login(
			@WebParam(name = "username", partName = "username") String username,
			@WebParam(name = "password", partName = "password") String password);

}
