package com.bonc.busi.sys.entity;

import com.alibaba.fastjson.annotation.JSONField;

import java.io.Serializable;
import java.util.Date;
public class PltActivityInfo implements Serializable {

    private String CHANNELID;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.REC_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer REC_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ACTIVITY_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ACTIVITY_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ACTIVITY_DIVISION
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_DIVISION")
    private String ACTIVITY_DIVISION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ACTIVITY_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ACTIVITY_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ACTIVITY_THEME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ACTIVITY_THEME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ACTIVITY_THEMEID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ACTIVITY_THEMEID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ACTIVITY_TYPE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ACTIVITY_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.BEGIN_DATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Date BEGIN_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.END_DATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Date END_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ORI_STATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ORI_STATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.CREATE_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String CREATE_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.CREATE_DATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Date CREATE_DATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ORG_RANGE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ORG_RANGE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.TENANT_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String TENANT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ACTIVITY_STATUS
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer ACTIVITY_STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ACTIVITY_DESC
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ACTIVITY_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.GROUP_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String GROUP_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.GROUP_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String GROUP_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ACTIVITY_LEVEL
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ACTIVITY_LEVEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.PARENT_ACTIVITY
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String PARENT_ACTIVITY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.POLICY_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String POLICY_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ORDER_GEN_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer ORDER_GEN_RULE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ORDER_LIFE_CYCLE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer ORDER_LIFE_CYCLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ORDER_UPDATE_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer ORDER_UPDATE_RULE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.FILTER_BLACKUSERLIST
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer FILTER_BLACKUSERLIST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.FILTER_WHITEUSERLIST
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer FILTER_WHITEUSERLIST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.DELETE_ACTIVITY_USER
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer DELETE_ACTIVITY_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.DELETE_SUCCESSRULE_USER
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer DELETE_SUCCESSRULE_USER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.IS_SENDORDER
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String IS_SENDORDER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ORG_LEVEL
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ORG_LEVEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.OTHER_CHANNEL_EXERULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String OTHER_CHANNEL_EXERULE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.SELF_SEND_CHANNEL_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String SELF_SEND_CHANNEL_RULE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.BEFORE_SUSPEND_STATUS
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Integer BEFORE_SUSPEND_STATUS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.STRATEGY_DESC
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String STRATEGY_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.LAST_ORDER_CREATE_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private Date LAST_ORDER_CREATE_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.ECHANNEL_SHOW_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String ECHANNEL_SHOW_RULE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_INFO.CHANNEL_SPECIALFILTER_LIST
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    private String CHANNEL_SPECIALFILTER_LIST;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.REC_ID
     *
     * @return the value of PLT_ACTIVITY_INFO.REC_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "REC_ID")
    public Integer getREC_ID() {
        return REC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.REC_ID
     *
     * @param REC_ID the value for PLT_ACTIVITY_INFO.REC_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setREC_ID(Integer REC_ID) {
        this.REC_ID = REC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_ID
     *
     * @return the value of PLT_ACTIVITY_INFO.ACTIVITY_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_ID")
    public String getACTIVITY_ID() {
        return ACTIVITY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_ID
     *
     * @param ACTIVITY_ID the value for PLT_ACTIVITY_INFO.ACTIVITY_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setACTIVITY_ID(String ACTIVITY_ID) {
        this.ACTIVITY_ID = ACTIVITY_ID == null ? null : ACTIVITY_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_DIVISION
     *
     * @return the value of PLT_ACTIVITY_INFO.ACTIVITY_DIVISION
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_DIVISION")
    public String getACTIVITY_DIVISION() {
        return ACTIVITY_DIVISION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_DIVISION
     *
     * @param ACTIVITY_DIVISION the value for PLT_ACTIVITY_INFO.ACTIVITY_DIVISION
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setACTIVITY_DIVISION(String ACTIVITY_DIVISION) {
        this.ACTIVITY_DIVISION = ACTIVITY_DIVISION == null ? null : ACTIVITY_DIVISION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_NAME
     *
     * @return the value of PLT_ACTIVITY_INFO.ACTIVITY_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_NAME")
    public String getACTIVITY_NAME() {
        return ACTIVITY_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_NAME
     *
     * @param ACTIVITY_NAME the value for PLT_ACTIVITY_INFO.ACTIVITY_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setACTIVITY_NAME(String ACTIVITY_NAME) {
        this.ACTIVITY_NAME = ACTIVITY_NAME == null ? null : ACTIVITY_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_THEME
     *
     * @return the value of PLT_ACTIVITY_INFO.ACTIVITY_THEME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_THEME")
    public String getACTIVITY_THEME() {
        return ACTIVITY_THEME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_THEME
     *
     * @param ACTIVITY_THEME the value for PLT_ACTIVITY_INFO.ACTIVITY_THEME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setACTIVITY_THEME(String ACTIVITY_THEME) {
        this.ACTIVITY_THEME = ACTIVITY_THEME == null ? null : ACTIVITY_THEME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_THEMEID
     *
     * @return the value of PLT_ACTIVITY_INFO.ACTIVITY_THEMEID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_THEMEID")
    public String getACTIVITY_THEMEID() {
        return ACTIVITY_THEMEID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_THEMEID
     *
     * @param ACTIVITY_THEMEID the value for PLT_ACTIVITY_INFO.ACTIVITY_THEMEID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setACTIVITY_THEMEID(String ACTIVITY_THEMEID) {
        this.ACTIVITY_THEMEID = ACTIVITY_THEMEID == null ? null : ACTIVITY_THEMEID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_TYPE
     *
     * @return the value of PLT_ACTIVITY_INFO.ACTIVITY_TYPE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_TYPE")
    public String getACTIVITY_TYPE() {
        return ACTIVITY_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_TYPE
     *
     * @param ACTIVITY_TYPE the value for PLT_ACTIVITY_INFO.ACTIVITY_TYPE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setACTIVITY_TYPE(String ACTIVITY_TYPE) {
        this.ACTIVITY_TYPE = ACTIVITY_TYPE == null ? null : ACTIVITY_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.BEGIN_DATE
     *
     * @return the value of PLT_ACTIVITY_INFO.BEGIN_DATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public Date getBEGIN_DATE() {
        return BEGIN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.BEGIN_DATE
     *
     * @param BEGIN_DATE the value for PLT_ACTIVITY_INFO.BEGIN_DATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setBEGIN_DATE(Date BEGIN_DATE) {
        this.BEGIN_DATE = BEGIN_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.END_DATE
     *
     * @return the value of PLT_ACTIVITY_INFO.END_DATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public Date getEND_DATE() {
        return END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.END_DATE
     *
     * @param END_DATE the value for PLT_ACTIVITY_INFO.END_DATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setEND_DATE(Date END_DATE) {
        this.END_DATE = END_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ORI_STATE
     *
     * @return the value of PLT_ACTIVITY_INFO.ORI_STATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ORI_STATE")
    public String getORI_STATE() {
        return ORI_STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ORI_STATE
     *
     * @param ORI_STATE the value for PLT_ACTIVITY_INFO.ORI_STATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setORI_STATE(String ORI_STATE) {
        this.ORI_STATE = ORI_STATE == null ? null : ORI_STATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.CREATE_NAME
     *
     * @return the value of PLT_ACTIVITY_INFO.CREATE_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "CREATE_NAME")
    public String getCREATE_NAME() {
        return CREATE_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.CREATE_NAME
     *
     * @param CREATE_NAME the value for PLT_ACTIVITY_INFO.CREATE_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setCREATE_NAME(String CREATE_NAME) {
        this.CREATE_NAME = CREATE_NAME == null ? null : CREATE_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.CREATE_DATE
     *
     * @return the value of PLT_ACTIVITY_INFO.CREATE_DATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public Date getCREATE_DATE() {
        return CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.CREATE_DATE
     *
     * @param CREATE_DATE the value for PLT_ACTIVITY_INFO.CREATE_DATE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setCREATE_DATE(Date CREATE_DATE) {
        this.CREATE_DATE = CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ORG_RANGE
     *
     * @return the value of PLT_ACTIVITY_INFO.ORG_RANGE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ORG_RANGE")
    public String getORG_RANGE() {
        return ORG_RANGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ORG_RANGE
     *
     * @param ORG_RANGE the value for PLT_ACTIVITY_INFO.ORG_RANGE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setORG_RANGE(String ORG_RANGE) {
        this.ORG_RANGE = ORG_RANGE == null ? null : ORG_RANGE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.TENANT_ID
     *
     * @return the value of PLT_ACTIVITY_INFO.TENANT_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "TENANT_ID")
    public String getTENANT_ID() {
        return TENANT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.TENANT_ID
     *
     * @param TENANT_ID the value for PLT_ACTIVITY_INFO.TENANT_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setTENANT_ID(String TENANT_ID) {
        this.TENANT_ID = TENANT_ID == null ? null : TENANT_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_STATUS
     *
     * @return the value of PLT_ACTIVITY_INFO.ACTIVITY_STATUS
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_STATUS")
    public Integer getACTIVITY_STATUS() {
        return ACTIVITY_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_STATUS
     *
     * @param ACTIVITY_STATUS the value for PLT_ACTIVITY_INFO.ACTIVITY_STATUS
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setACTIVITY_STATUS(Integer ACTIVITY_STATUS) {
        this.ACTIVITY_STATUS = ACTIVITY_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_DESC
     *
     * @return the value of PLT_ACTIVITY_INFO.ACTIVITY_DESC
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_DESC")
    public String getACTIVITY_DESC() {
        return ACTIVITY_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_DESC
     *
     * @param ACTIVITY_DESC the value for PLT_ACTIVITY_INFO.ACTIVITY_DESC
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setACTIVITY_DESC(String ACTIVITY_DESC) {
        this.ACTIVITY_DESC = ACTIVITY_DESC == null ? null : ACTIVITY_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.GROUP_ID
     *
     * @return the value of PLT_ACTIVITY_INFO.GROUP_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "GROUP_ID")
    public String getGROUP_ID() {
        return GROUP_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.GROUP_ID
     *
     * @param GROUP_ID the value for PLT_ACTIVITY_INFO.GROUP_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setGROUP_ID(String GROUP_ID) {
        this.GROUP_ID = GROUP_ID == null ? null : GROUP_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.GROUP_NAME
     *
     * @return the value of PLT_ACTIVITY_INFO.GROUP_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "GROUP_NAME")
    public String getGROUP_NAME() {
        return GROUP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.GROUP_NAME
     *
     * @param GROUP_NAME the value for PLT_ACTIVITY_INFO.GROUP_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setGROUP_NAME(String GROUP_NAME) {
        this.GROUP_NAME = GROUP_NAME == null ? null : GROUP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_LEVEL
     *
     * @return the value of PLT_ACTIVITY_INFO.ACTIVITY_LEVEL
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ACTIVITY_LEVEL")
    public String getACTIVITY_LEVEL() {
        return ACTIVITY_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ACTIVITY_LEVEL
     *
     * @param ACTIVITY_LEVEL the value for PLT_ACTIVITY_INFO.ACTIVITY_LEVEL
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setACTIVITY_LEVEL(String ACTIVITY_LEVEL) {
        this.ACTIVITY_LEVEL = ACTIVITY_LEVEL == null ? null : ACTIVITY_LEVEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.PARENT_ACTIVITY
     *
     * @return the value of PLT_ACTIVITY_INFO.PARENT_ACTIVITY
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "PARENT_ACTIVITY")
    public String getPARENT_ACTIVITY() {
        return PARENT_ACTIVITY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.PARENT_ACTIVITY
     *
     * @param PARENT_ACTIVITY the value for PLT_ACTIVITY_INFO.PARENT_ACTIVITY
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setPARENT_ACTIVITY(String PARENT_ACTIVITY) {
        this.PARENT_ACTIVITY = PARENT_ACTIVITY == null ? null : PARENT_ACTIVITY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.POLICY_ID
     *
     * @return the value of PLT_ACTIVITY_INFO.POLICY_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "POLICY_ID")
    public String getPOLICY_ID() {
        return POLICY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.POLICY_ID
     *
     * @param POLICY_ID the value for PLT_ACTIVITY_INFO.POLICY_ID
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setPOLICY_ID(String POLICY_ID) {
        this.POLICY_ID = POLICY_ID == null ? null : POLICY_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ORDER_GEN_RULE
     *
     * @return the value of PLT_ACTIVITY_INFO.ORDER_GEN_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ORDER_GEN_RULE")
    public Integer getORDER_GEN_RULE() {
        return ORDER_GEN_RULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ORDER_GEN_RULE
     *
     * @param ORDER_GEN_RULE the value for PLT_ACTIVITY_INFO.ORDER_GEN_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setORDER_GEN_RULE(Integer ORDER_GEN_RULE) {
        this.ORDER_GEN_RULE = ORDER_GEN_RULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ORDER_LIFE_CYCLE
     *
     * @return the value of PLT_ACTIVITY_INFO.ORDER_LIFE_CYCLE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ORDER_LIFE_CYCLE")
    public Integer getORDER_LIFE_CYCLE() {
        return ORDER_LIFE_CYCLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ORDER_LIFE_CYCLE
     *
     * @param ORDER_LIFE_CYCLE the value for PLT_ACTIVITY_INFO.ORDER_LIFE_CYCLE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setORDER_LIFE_CYCLE(Integer ORDER_LIFE_CYCLE) {
        this.ORDER_LIFE_CYCLE = ORDER_LIFE_CYCLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ORDER_UPDATE_RULE
     *
     * @return the value of PLT_ACTIVITY_INFO.ORDER_UPDATE_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ORDER_UPDATE_RULE")
    public Integer getORDER_UPDATE_RULE() {
        return ORDER_UPDATE_RULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ORDER_UPDATE_RULE
     *
     * @param ORDER_UPDATE_RULE the value for PLT_ACTIVITY_INFO.ORDER_UPDATE_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setORDER_UPDATE_RULE(Integer ORDER_UPDATE_RULE) {
        this.ORDER_UPDATE_RULE = ORDER_UPDATE_RULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.FILTER_BLACKUSERLIST
     *
     * @return the value of PLT_ACTIVITY_INFO.FILTER_BLACKUSERLIST
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "FILTER_BLACKUSERLIST")
    public Integer getFILTER_BLACKUSERLIST() {
        return FILTER_BLACKUSERLIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.FILTER_BLACKUSERLIST
     *
     * @param FILTER_BLACKUSERLIST the value for PLT_ACTIVITY_INFO.FILTER_BLACKUSERLIST
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setFILTER_BLACKUSERLIST(Integer FILTER_BLACKUSERLIST) {
        this.FILTER_BLACKUSERLIST = FILTER_BLACKUSERLIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.FILTER_WHITEUSERLIST
     *
     * @return the value of PLT_ACTIVITY_INFO.FILTER_WHITEUSERLIST
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "FILTER_WHITEUSERLIST")
    public Integer getFILTER_WHITEUSERLIST() {
        return FILTER_WHITEUSERLIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.FILTER_WHITEUSERLIST
     *
     * @param FILTER_WHITEUSERLIST the value for PLT_ACTIVITY_INFO.FILTER_WHITEUSERLIST
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setFILTER_WHITEUSERLIST(Integer FILTER_WHITEUSERLIST) {
        this.FILTER_WHITEUSERLIST = FILTER_WHITEUSERLIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.DELETE_ACTIVITY_USER
     *
     * @return the value of PLT_ACTIVITY_INFO.DELETE_ACTIVITY_USER
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "DELETE_ACTIVITY_USER")
    public Integer getDELETE_ACTIVITY_USER() {
        return DELETE_ACTIVITY_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.DELETE_ACTIVITY_USER
     *
     * @param DELETE_ACTIVITY_USER the value for PLT_ACTIVITY_INFO.DELETE_ACTIVITY_USER
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setDELETE_ACTIVITY_USER(Integer DELETE_ACTIVITY_USER) {
        this.DELETE_ACTIVITY_USER = DELETE_ACTIVITY_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.DELETE_SUCCESSRULE_USER
     *
     * @return the value of PLT_ACTIVITY_INFO.DELETE_SUCCESSRULE_USER
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "DELETE_SUCCESSRULE_USER")
    public Integer getDELETE_SUCCESSRULE_USER() {
        return DELETE_SUCCESSRULE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.DELETE_SUCCESSRULE_USER
     *
     * @param DELETE_SUCCESSRULE_USER the value for PLT_ACTIVITY_INFO.DELETE_SUCCESSRULE_USER
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setDELETE_SUCCESSRULE_USER(Integer DELETE_SUCCESSRULE_USER) {
        this.DELETE_SUCCESSRULE_USER = DELETE_SUCCESSRULE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.IS_SENDORDER
     *
     * @return the value of PLT_ACTIVITY_INFO.IS_SENDORDER
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "IS_SENDORDER")
    public String getIS_SENDORDER() {
        return IS_SENDORDER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.IS_SENDORDER
     *
     * @param IS_SENDORDER the value for PLT_ACTIVITY_INFO.IS_SENDORDER
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setIS_SENDORDER(String IS_SENDORDER) {
        this.IS_SENDORDER = IS_SENDORDER == null ? null : IS_SENDORDER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ORG_LEVEL
     *
     * @return the value of PLT_ACTIVITY_INFO.ORG_LEVEL
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ORG_LEVEL")
    public String getORG_LEVEL() {
        return ORG_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ORG_LEVEL
     *
     * @param ORG_LEVEL the value for PLT_ACTIVITY_INFO.ORG_LEVEL
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setORG_LEVEL(String ORG_LEVEL) {
        this.ORG_LEVEL = ORG_LEVEL == null ? null : ORG_LEVEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.OTHER_CHANNEL_EXERULE
     *
     * @return the value of PLT_ACTIVITY_INFO.OTHER_CHANNEL_EXERULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "OTHER_CHANNEL_EXERULE")
    public String getOTHER_CHANNEL_EXERULE() {
        return OTHER_CHANNEL_EXERULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.OTHER_CHANNEL_EXERULE
     *
     * @param OTHER_CHANNEL_EXERULE the value for PLT_ACTIVITY_INFO.OTHER_CHANNEL_EXERULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setOTHER_CHANNEL_EXERULE(String OTHER_CHANNEL_EXERULE) {
        this.OTHER_CHANNEL_EXERULE = OTHER_CHANNEL_EXERULE == null ? null : OTHER_CHANNEL_EXERULE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.SELF_SEND_CHANNEL_RULE
     *
     * @return the value of PLT_ACTIVITY_INFO.SELF_SEND_CHANNEL_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "SELF_SEND_CHANNEL_RULE")
    public String getSELF_SEND_CHANNEL_RULE() {
        return SELF_SEND_CHANNEL_RULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.SELF_SEND_CHANNEL_RULE
     *
     * @param SELF_SEND_CHANNEL_RULE the value for PLT_ACTIVITY_INFO.SELF_SEND_CHANNEL_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setSELF_SEND_CHANNEL_RULE(String SELF_SEND_CHANNEL_RULE) {
        this.SELF_SEND_CHANNEL_RULE = SELF_SEND_CHANNEL_RULE == null ? null : SELF_SEND_CHANNEL_RULE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.BEFORE_SUSPEND_STATUS
     *
     * @return the value of PLT_ACTIVITY_INFO.BEFORE_SUSPEND_STATUS
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "BEFORE_SUSPEND_STATUS")
    public Integer getBEFORE_SUSPEND_STATUS() {
        return BEFORE_SUSPEND_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.BEFORE_SUSPEND_STATUS
     *
     * @param BEFORE_SUSPEND_STATUS the value for PLT_ACTIVITY_INFO.BEFORE_SUSPEND_STATUS
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setBEFORE_SUSPEND_STATUS(Integer BEFORE_SUSPEND_STATUS) {
        this.BEFORE_SUSPEND_STATUS = BEFORE_SUSPEND_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.STRATEGY_DESC
     *
     * @return the value of PLT_ACTIVITY_INFO.STRATEGY_DESC
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "STRATEGY_DESC")
    public String getSTRATEGY_DESC() {
        return STRATEGY_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.STRATEGY_DESC
     *
     * @param STRATEGY_DESC the value for PLT_ACTIVITY_INFO.STRATEGY_DESC
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setSTRATEGY_DESC(String STRATEGY_DESC) {
        this.STRATEGY_DESC = STRATEGY_DESC == null ? null : STRATEGY_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.LAST_ORDER_CREATE_TIME
     *
     * @return the value of PLT_ACTIVITY_INFO.LAST_ORDER_CREATE_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public Date getLAST_ORDER_CREATE_TIME() {
        return LAST_ORDER_CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.LAST_ORDER_CREATE_TIME
     *
     * @param LAST_ORDER_CREATE_TIME the value for PLT_ACTIVITY_INFO.LAST_ORDER_CREATE_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setLAST_ORDER_CREATE_TIME(Date LAST_ORDER_CREATE_TIME) {
        this.LAST_ORDER_CREATE_TIME = LAST_ORDER_CREATE_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.ECHANNEL_SHOW_RULE
     *
     * @return the value of PLT_ACTIVITY_INFO.ECHANNEL_SHOW_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "ECHANNEL_SHOW_RULE")
    public String getECHANNEL_SHOW_RULE() {
        return ECHANNEL_SHOW_RULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.ECHANNEL_SHOW_RULE
     *
     * @param ECHANNEL_SHOW_RULE the value for PLT_ACTIVITY_INFO.ECHANNEL_SHOW_RULE
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setECHANNEL_SHOW_RULE(String ECHANNEL_SHOW_RULE) {
        this.ECHANNEL_SHOW_RULE = ECHANNEL_SHOW_RULE == null ? null : ECHANNEL_SHOW_RULE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_INFO.CHANNEL_SPECIALFILTER_LIST
     *
     * @return the value of PLT_ACTIVITY_INFO.CHANNEL_SPECIALFILTER_LIST
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    @JSONField( name = "CHANNEL_SPECIALFILTER_LIST")
    public String getCHANNEL_SPECIALFILTER_LIST() {
        return CHANNEL_SPECIALFILTER_LIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_INFO.CHANNEL_SPECIALFILTER_LIST
     *
     * @param CHANNEL_SPECIALFILTER_LIST the value for PLT_ACTIVITY_INFO.CHANNEL_SPECIALFILTER_LIST
     *
     * @mbggenerated Mon Dec 05 17:01:24 CST 2016
     */
    public void setCHANNEL_SPECIALFILTER_LIST(String CHANNEL_SPECIALFILTER_LIST) {
        this.CHANNEL_SPECIALFILTER_LIST = CHANNEL_SPECIALFILTER_LIST == null ? null : CHANNEL_SPECIALFILTER_LIST.trim();
    }
    
    private String PARENT_ACTIVITY_NAME;
    private String PARENT_ACTIVITY_STARTDATE;
    private String PARENT_ACTIVITY_ENDDATE;
    private String PARENT_PROVID;
    
    public void setPARENT_ACTIVITY_NAME (String name) {
    	this.PARENT_ACTIVITY_NAME = name;
    }
    @JSONField( name = "PARENT_ACTIVITY_NAME")
    public String getPARENT_ACTIVITY_NAME() {
    	return PARENT_ACTIVITY_NAME;
    }
    public void setPARENT_ACTIVITY_STARTDATE (String start) {
    	this.PARENT_ACTIVITY_STARTDATE = start;
    }
    @JSONField( name = "PARENT_ACTIVITY_STARTDATE")
    public String getPARENT_ACTIVITY_STARTDATE() {
    	return PARENT_ACTIVITY_STARTDATE;
    }
    public void setPARENT_ACTIVITY_ENDDATE (String end) {
    	this.PARENT_ACTIVITY_ENDDATE = end;
    }
    @JSONField( name = "PARENT_ACTIVITY_ENDDATE")
    public String getPARENT_ACTIVITY_ENDDATE() {
    	return PARENT_ACTIVITY_ENDDATE;
    }
    public void setPARENT_PROVID(String pro) {
    	this.PARENT_PROVID = pro;
    }
    @JSONField( name = "PARENT_PROVID")
    public String getPARENT_PROVID() {
    	return PARENT_PROVID;
    }
    
    private String CREATOR_ORGID;
    private String CREATOR_ORG_PATH;
    private String USERGROUP_FILTERCON;
    public void setCREATOR_ORGID(String id) {
    	this.CREATOR_ORGID = id;
    }
    @JSONField( name = "CREATOR_ORGID")
    public String getCREATOR_ORGID() {
    	return CREATOR_ORGID;
    }
    public void setCREATOR_ORG_PATH(String pro) {
    	this.CREATOR_ORG_PATH = pro;
    }
    @JSONField( name = "CREATOR_ORG_PATH")
    public String getCREATOR_ORG_PATH() {
    	return CREATOR_ORG_PATH;
    }
    public void setUSERGROUP_FILTERCON(String pro) {
    	this.USERGROUP_FILTERCON = pro;
    }
    @JSONField( name = "USERGROUP_FILTERCON")
    public String getUSERGROUP_FILTERCON() {
    	return USERGROUP_FILTERCON;
    }
    
    private Date ORDER_BEGIN_DATE;
    private Date ORDER_END_DATE;
    public void setORDER_BEGIN_DATE(Date begindate) {
    	this.ORDER_BEGIN_DATE = begindate;
    }
    @JSONField( name = "ORDER_BEGIN_DATE")
    public Date getORDER_BEGIN_DATE() {
    	return ORDER_BEGIN_DATE;
    }
    public void setORDER_END_DATE(Date enddate) {
    	this.ORDER_END_DATE = enddate;
    }
    @JSONField( name = "ORDER_END_DATE")
    public Date getORDER_END_DATE() {
    	return ORDER_END_DATE;
    }
    private Integer REMAIN_PERCENT;
    @JSONField( name = "REMAIN_PERCENT")
	public Integer getREMAIN_PERCENT() {
		return REMAIN_PERCENT;
	}

	public void setREMAIN_PERCENT(Integer percent) {
		REMAIN_PERCENT = percent;
	}
    @JSONField( name = "CHANNELID")
    public String getCHANNELID() {
        return CHANNELID;
    }

    public void setCHANNELID(String CHANNELID) {
        this.CHANNELID = CHANNELID;
    }
    
	// 奖励描述
	private String REWARD_DESC;
	// 电信项目-渠道协同
	private String CHANNEL_SYNERGISM;

	public String getREWARD_DESC() {
		return REWARD_DESC;
	}

	public void setREWARD_DESC(String rEWARD_DESC) {
		REWARD_DESC = rEWARD_DESC;
	}

	public String getCHANNEL_SYNERGISM() {
		return CHANNEL_SYNERGISM;
	}

	public void setCHANNEL_SYNERGISM(String cHANNEL_SYNERGISM) {
		CHANNEL_SYNERGISM = cHANNEL_SYNERGISM;
	}
}