package com.bonc.busi.sys.entity;

import java.io.Serializable;
import java.util.Date;

public class SysLog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.ID
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.TENANT_ID
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private String TENANT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.LOG_TIME
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private Date LOG_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.APP_NAME
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private String APP_NAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.BUSI_ITEM_1
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private String BUSI_ITEM_1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.BUSI_ITEM_2
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private String BUSI_ITEM_2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.BUSI_ITEM_3
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private String BUSI_ITEM_3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.BUSI_ITEM_4
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private String BUSI_ITEM_4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.BUSI_ITEM_5
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private String BUSI_ITEM_5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_LOG.LOG_MESSAGE
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    private String LOG_MESSAGE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.ID
     *
     * @return the value of SYS_LOG.ID
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.ID
     *
     * @param ID the value for SYS_LOG.ID
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.TENANT_ID
     *
     * @return the value of SYS_LOG.TENANT_ID
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public String getTENANT_ID() {
        return TENANT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.TENANT_ID
     *
     * @param TENANT_ID the value for SYS_LOG.TENANT_ID
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setTENANT_ID(String TENANT_ID) {
        this.TENANT_ID = TENANT_ID == null ? null : TENANT_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.LOG_TIME
     *
     * @return the value of SYS_LOG.LOG_TIME
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public Date getLOG_TIME() {
        return LOG_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.LOG_TIME
     *
     * @param LOG_TIME the value for SYS_LOG.LOG_TIME
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setLOG_TIME(Date LOG_TIME) {
        this.LOG_TIME = LOG_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.APP_NAME
     *
     * @return the value of SYS_LOG.APP_NAME
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public String getAPP_NAME() {
        return APP_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.APP_NAME
     *
     * @param APP_NAME the value for SYS_LOG.APP_NAME
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setAPP_NAME(String APP_NAME) {
        this.APP_NAME = APP_NAME == null ? null : APP_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.BUSI_ITEM_1
     *
     * @return the value of SYS_LOG.BUSI_ITEM_1
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public String getBUSI_ITEM_1() {
        return BUSI_ITEM_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.BUSI_ITEM_1
     *
     * @param BUSI_ITEM_1 the value for SYS_LOG.BUSI_ITEM_1
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setBUSI_ITEM_1(String BUSI_ITEM_1) {
        this.BUSI_ITEM_1 = BUSI_ITEM_1 == null ? null : BUSI_ITEM_1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.BUSI_ITEM_2
     *
     * @return the value of SYS_LOG.BUSI_ITEM_2
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public String getBUSI_ITEM_2() {
        return BUSI_ITEM_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.BUSI_ITEM_2
     *
     * @param BUSI_ITEM_2 the value for SYS_LOG.BUSI_ITEM_2
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setBUSI_ITEM_2(String BUSI_ITEM_2) {
        this.BUSI_ITEM_2 = BUSI_ITEM_2 == null ? null : BUSI_ITEM_2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.BUSI_ITEM_3
     *
     * @return the value of SYS_LOG.BUSI_ITEM_3
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public String getBUSI_ITEM_3() {
        return BUSI_ITEM_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.BUSI_ITEM_3
     *
     * @param BUSI_ITEM_3 the value for SYS_LOG.BUSI_ITEM_3
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setBUSI_ITEM_3(String BUSI_ITEM_3) {
        this.BUSI_ITEM_3 = BUSI_ITEM_3 == null ? null : BUSI_ITEM_3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.BUSI_ITEM_4
     *
     * @return the value of SYS_LOG.BUSI_ITEM_4
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public String getBUSI_ITEM_4() {
        return BUSI_ITEM_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.BUSI_ITEM_4
     *
     * @param BUSI_ITEM_4 the value for SYS_LOG.BUSI_ITEM_4
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setBUSI_ITEM_4(String BUSI_ITEM_4) {
        this.BUSI_ITEM_4 = BUSI_ITEM_4 == null ? null : BUSI_ITEM_4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.BUSI_ITEM_5
     *
     * @return the value of SYS_LOG.BUSI_ITEM_5
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public String getBUSI_ITEM_5() {
        return BUSI_ITEM_5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.BUSI_ITEM_5
     *
     * @param BUSI_ITEM_5 the value for SYS_LOG.BUSI_ITEM_5
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setBUSI_ITEM_5(String BUSI_ITEM_5) {
        this.BUSI_ITEM_5 = BUSI_ITEM_5 == null ? null : BUSI_ITEM_5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_LOG.LOG_MESSAGE
     *
     * @return the value of SYS_LOG.LOG_MESSAGE
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public String getLOG_MESSAGE() {
        return LOG_MESSAGE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_LOG.LOG_MESSAGE
     *
     * @param LOG_MESSAGE the value for SYS_LOG.LOG_MESSAGE
     *
     * @mbggenerated Sat May 27 16:46:31 CST 2017
     */
    public void setLOG_MESSAGE(String LOG_MESSAGE) {
        this.LOG_MESSAGE = LOG_MESSAGE == null ? null : LOG_MESSAGE.trim();
    }
}