INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ACTIVITYINTER_ACTHUASHU', 'http://aaaaactivity/activity/actHuaShu', '活动话术变量接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ACTIVITY_DIVIDE_STATUS', 'http://xxxxxassignment/ruleInter/getStatus', '资源划配获取划配状态接口--工单生成用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ACTIVITY_INFO', 'http://aaaaactivity/restful/activity/ActivityRuleList', '获取活动列表接口--工单生成调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ACTIVITY_INFO_DETAIL', 'http://aaaaactivity/restful/activity/ActivityInfo', '活动详情接口--工单生成调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ACT_HUA_SHU', 'http://aaaaactivity/restful/common/get/varGetListInfo', '话术变量请求接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ACTIVITY_MULT_DIVIDE', 'http://xxxxxassignment/ruleInter/ruleTypes', '资源划配接口--工单生成调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ASYNBLACKANDWHITE.SERVICE.URL', 'http://ooooordertasksche2/service/asynblackandwhite', '调用接口同步黑白名单数据');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ASYNUSER.SERVICE.URL', 'http://ooooordertasksche2/service/asynuserlabel', '同步用户标签表--工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('CHANNELSTOP.SMS', 'http://smscenter:8080/csmscenter/interface/stopSendSms', '活动失效短信渠道消息通知地址');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('COCHANNEL_INIT_URL', 'http://ccccchannelmanager/statistic/initHandle', '渠道接口 当一个批次工单生成完成之后调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('CHANNEL_COORD_ADD_URL', 'http://ccccchannelcoord/v2/addContactRecordBatch', null);
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('DATA_SEND_URL', 'http://132.35.227.79:9980/dataservice/webservice/dataSendService', 'channel');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GENORDER.SERVICE.URL', 'http://ooooordertask2/service/generateOrder', '工单生成服务接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_BENCHLIST_URL', 'http://ooooordertaskservice/activity/getAllSeqValidInfo', '获取有效和无效的活动批次--工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_INITNUM_URL', 'http://ooooordertaskservice/activity/getOrderCount', '获取工单数量接口--工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_MONTH_TIME', 'http://aaaaactivity/restful/common/get/CommonDate', '获取账期url');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_TABLES_URL', 'http://ooooordertaskservice/activity/getOrderTableListByChannel', '根据渠道获取工单表名接口--工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_TABLE_URL', 'http://ooooordertaskservice/activity/getOrderTableName', '获取路由工单表名接口--工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_PHONE_TABLE_URL', 'http://ooooordertaskservice/activity/getOrderTableNamesByPhoneAndChannelId', '根据手机号渠道号查询工单表名--工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_TASK_BACK_URL', 'http://ooooordertaskservice/activity/updateExecuteInterfaceStatus', '获取可执行的渠道列表--工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_TASK_URL', 'http://ooooordertaskservice/activity/getExecuteableActivitySeqs', '获取可执行的批次--工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_USER_FIELD_MAP', 'http://ooooordertaskservice/activity/getOrderTableColumnMap', '获取工单表列名映射状态--工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_USER_GROUP_SQL', 'http://xxxxxlabel/restful/lableAction/getCustGroupSql', '获取用户群sql接口--工单生成调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDERCENTER_FEEDBACK', 'http://cccccchannalmanager/interface/channel/caontact', 'channel回执处理URL');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDERCHECK.SCENEMARKET.URL', 'http://ssssscenemarketing/activitysc/updataReportByOrder', '成功标准跑完调用场景营销url');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDERCHECK.SUCESS.SERVICE.URL', 'http://ooooordertasksche2/service/ordersucesscheck/{TENANT_ID}', '事后成功检查接口 --工单服务内部调用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDERFAILURE.SERVICE.URL', 'http://ooooordertasksche2/failure/orderFailure/{TENANT_ID}', '工单失效远程调度orderSchedule2URL');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDERFAILURE.UPDATE.OREDER.NUM.URL', 'http://ooooordertaskservice/activity/updateOrderTableUsingInfo', '失效移历史更新工单数量接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDERSERVICE_GETORDERTABLENAME', 'http://ooooordertaskservice/activity/getOrderTableName', '工单服务接口 获取表名');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDERUSERLABELUPDATE.STATISTIC.URL', 'http://ccccchannelmanager/statistic/successHandle', null);
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDER_CHECK_ENABLECHANNEL', 'http://caaaaactivity/activity/enableChannel', '工单生成查询权限接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDER_POPIN_ADDINDEX', 'http://ooooordertasksche2/service/popwinaddindex', '弹窗渠道生成手机号索引');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('ORDER_SUCESSFILTER_URL', 'http://ooooordertasksche2/service/ordersucessfilter', '成功标准url');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('SMSINTERFACE_FAILSMSLIST', 'http://sssssmsinterface/sms/cjyx/failsmslist', '场景营销更新失败短信接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('CHANNEL_COORD_BENCH_URL', 'http://ccccchannelcoord/v2/channelCoordBatch', '渠道协同-批量工单有效查询接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('CHANNEL_COORD_FIND_VALID_URL', 'http://ccccchannelcoord/v2/channelCoord', '渠道协同-工单有效查询接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_GATE_WAY_INFO', 'http://sssssmsinterface/smsSet/getGatewayInfoByTenId', '短信网关查询接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_SMS_BENCH_FAL_URL', 'http://sssssmsinterface/sms/failsmslist', '短信发送失败批量信息');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_SMS_BENCH_SUC_URL', 'http://sssssmsinterface/sms/succsmslist', '短信发送成功批量信息');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_SMS_SIGN_FAL_URL', 'http://sssssmsinterface/sms/failsmssingle', '短信发送失败信息');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_SMS_SIGN_SUC_URL', 'http://sssssmsinterface/sms/succsmssingle', '短信发送成功信息');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('OUTCALL.CHANNELCFG.URL', 'http://aaaaactivity/activity/companyInfo', '获取电话渠道FTP等信息URL');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('CHANNEL_CALL_TASK', 'http://ccccchannelmanager/task/call/', '调度任务的接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('CHANNEL_GET_TASK', 'http://ccccchannelmanager/statistic/getTask', '获取任务列表的接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_CHANNEL_MANAGER_DAYTASK_URL', 'http://ccccchannelmanager/statistic/dayTask', '渠道中心日定时任务URL');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_CONTACT_STATISTIC_URL', 'http://ccccchannelmanager/statistic/contactStatistic', '渠道中心定时同接触统计');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_GENTASK_URL', 'http://ccccchannelmanager/statistic/dayGenTask', '短信发送统计接口');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_SMS_STATISTIC_URL', 'http://sssssmsinterface/statistics', '渠道中心日定时任务URL');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_GENTASK_URL', 'http://ccccchannelmanager/statistic/dayGenTask', '渠道中心日定时任务URL');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_ALLOTORDER_URL', 'http://172.16.14.12:8090/eframeone/allotcenter/allot/allotOrder', '电信虚拟渠道工单调配');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_CREATE_ORDER_MAPPING', 'http://ooooordertaskservice/order/createChannelOrderMapping', '工单创建初始化 渠道工单映射表');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_STORE_LABEL', 'http://ooooordertaskservice/userlabel/storeDemandLabel', '保存渠道注册需要同步的标签到表中，供用户标签同步使用');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('GET_STORE_REFRESH_ORDER', 'http://ooooordertaskservice/userlabel/storeRefreshOrderUsedLabel', '保存刷新工单数据时需要刷新的用户标签数据');
INSERT INTO  SYS_COMMON_CFG (CFG_KEY, CFG_VALUE, NOTE) VALUES ('CHANNEL_NOTICE_ADDRESS', '', '注册渠道后通知活动测');

