package com.bonc.busi.entity;

import java.io.Serializable;
import java.lang.reflect.Method;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.bonc.utils.TimeUtil;

@SuppressWarnings("serial")
public class PltCommonLog implements Serializable {
	
	private static Log log = LogFactory.getLog(PltCommonLog.class);
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.ID
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.SERIAL_ID
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Integer SERIAL_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.TENANT_ID
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String TENANT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.LOG_TYPE
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String LOG_TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.SPONSOR
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String SPONSOR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.YYMMDD
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Integer YYMMDD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.START_TIME
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Date START_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.END_TIME
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Date END_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.DURATION
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Integer DURATION;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_CODE
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.DEST_NUM
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Integer DEST_NUM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_DESC
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_DESC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_NUM_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Integer BUSI_NUM_1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_NUM_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Integer BUSI_NUM_2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_TIME_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Date BUSI_TIME_1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_TIME_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private Date BUSI_TIME_2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_MONEY_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private BigDecimal BUSI_MONEY_1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_MONEY_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private BigDecimal BUSI_MONEY_2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_3
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_4
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_5
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_6
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_7
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_8
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_9
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_10
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_11
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_12
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_13
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_14
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_COMMON_LOG.BUSI_ITEM_15
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    private String BUSI_ITEM_15;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.ID
     *
     * @return the value of PLT_COMMON_LOG.ID
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.ID
     *
     * @param ID the value for PLT_COMMON_LOG.ID
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.SERIAL_ID
     *
     * @return the value of PLT_COMMON_LOG.SERIAL_ID
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Integer getSERIAL_ID() {
        return SERIAL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.SERIAL_ID
     *
     * @param SERIAL_ID the value for PLT_COMMON_LOG.SERIAL_ID
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setSERIAL_ID(Integer SERIAL_ID) {
        this.SERIAL_ID = SERIAL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.TENANT_ID
     *
     * @return the value of PLT_COMMON_LOG.TENANT_ID
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getTENANT_ID() {
        return TENANT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.TENANT_ID
     *
     * @param TENANT_ID the value for PLT_COMMON_LOG.TENANT_ID
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setTENANT_ID(String TENANT_ID) {
        this.TENANT_ID = TENANT_ID == null ? null : TENANT_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.LOG_TYPE
     *
     * @return the value of PLT_COMMON_LOG.LOG_TYPE
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getLOG_TYPE() {
        return LOG_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.LOG_TYPE
     *
     * @param LOG_TYPE the value for PLT_COMMON_LOG.LOG_TYPE
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setLOG_TYPE(String LOG_TYPE) {
        this.LOG_TYPE = LOG_TYPE == null ? null : LOG_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.SPONSOR
     *
     * @return the value of PLT_COMMON_LOG.SPONSOR
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getSPONSOR() {
        return SPONSOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.SPONSOR
     *
     * @param SPONSOR the value for PLT_COMMON_LOG.SPONSOR
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setSPONSOR(String SPONSOR) {
        this.SPONSOR = SPONSOR == null ? null : SPONSOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.YYMMDD
     *
     * @return the value of PLT_COMMON_LOG.YYMMDD
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Integer getYYMMDD() {
        return YYMMDD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.YYMMDD
     *
     * @param YYMMDD the value for PLT_COMMON_LOG.YYMMDD
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setYYMMDD(Integer YYMMDD) {
        this.YYMMDD = YYMMDD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.START_TIME
     *
     * @return the value of PLT_COMMON_LOG.START_TIME
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Date getSTART_TIME() {
        return START_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.START_TIME
     *
     * @param START_TIME the value for PLT_COMMON_LOG.START_TIME
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setSTART_TIME(Date START_TIME) {
        this.START_TIME = START_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.END_TIME
     *
     * @return the value of PLT_COMMON_LOG.END_TIME
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Date getEND_TIME() {
        return END_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.END_TIME
     *
     * @param END_TIME the value for PLT_COMMON_LOG.END_TIME
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setEND_TIME(Date END_TIME) {
        this.END_TIME = END_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.DURATION
     *
     * @return the value of PLT_COMMON_LOG.DURATION
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Integer getDURATION() {
        return DURATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.DURATION
     *
     * @param DURATION the value for PLT_COMMON_LOG.DURATION
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setDURATION(Integer DURATION) {
        this.DURATION = DURATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_CODE
     *
     * @return the value of PLT_COMMON_LOG.BUSI_CODE
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_CODE() {
        return BUSI_CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_CODE
     *
     * @param BUSI_CODE the value for PLT_COMMON_LOG.BUSI_CODE
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_CODE(String BUSI_CODE) {
        this.BUSI_CODE = BUSI_CODE == null ? null : BUSI_CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.DEST_NUM
     *
     * @return the value of PLT_COMMON_LOG.DEST_NUM
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Integer getDEST_NUM() {
        return DEST_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.DEST_NUM
     *
     * @param DEST_NUM the value for PLT_COMMON_LOG.DEST_NUM
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setDEST_NUM(Integer DEST_NUM) {
        this.DEST_NUM = DEST_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_DESC
     *
     * @return the value of PLT_COMMON_LOG.BUSI_DESC
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_DESC() {
        return BUSI_DESC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_DESC
     *
     * @param BUSI_DESC the value for PLT_COMMON_LOG.BUSI_DESC
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_DESC(String BUSI_DESC) {
        this.BUSI_DESC = BUSI_DESC == null ? null : BUSI_DESC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_NUM_1
     *
     * @return the value of PLT_COMMON_LOG.BUSI_NUM_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Integer getBUSI_NUM_1() {
        return BUSI_NUM_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_NUM_1
     *
     * @param BUSI_NUM_1 the value for PLT_COMMON_LOG.BUSI_NUM_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_NUM_1(Integer BUSI_NUM_1) {
        this.BUSI_NUM_1 = BUSI_NUM_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_NUM_2
     *
     * @return the value of PLT_COMMON_LOG.BUSI_NUM_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Integer getBUSI_NUM_2() {
        return BUSI_NUM_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_NUM_2
     *
     * @param BUSI_NUM_2 the value for PLT_COMMON_LOG.BUSI_NUM_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_NUM_2(Integer BUSI_NUM_2) {
        this.BUSI_NUM_2 = BUSI_NUM_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_TIME_1
     *
     * @return the value of PLT_COMMON_LOG.BUSI_TIME_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Date getBUSI_TIME_1() {
        return BUSI_TIME_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_TIME_1
     *
     * @param BUSI_TIME_1 the value for PLT_COMMON_LOG.BUSI_TIME_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_TIME_1(Date BUSI_TIME_1) {
        this.BUSI_TIME_1 = BUSI_TIME_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_TIME_2
     *
     * @return the value of PLT_COMMON_LOG.BUSI_TIME_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public Date getBUSI_TIME_2() {
        return BUSI_TIME_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_TIME_2
     *
     * @param BUSI_TIME_2 the value for PLT_COMMON_LOG.BUSI_TIME_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_TIME_2(Date BUSI_TIME_2) {
        this.BUSI_TIME_2 = BUSI_TIME_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_MONEY_1
     *
     * @return the value of PLT_COMMON_LOG.BUSI_MONEY_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public BigDecimal getBUSI_MONEY_1() {
        return BUSI_MONEY_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_MONEY_1
     *
     * @param BUSI_MONEY_1 the value for PLT_COMMON_LOG.BUSI_MONEY_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_MONEY_1(BigDecimal BUSI_MONEY_1) {
        this.BUSI_MONEY_1 = BUSI_MONEY_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_MONEY_2
     *
     * @return the value of PLT_COMMON_LOG.BUSI_MONEY_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public BigDecimal getBUSI_MONEY_2() {
        return BUSI_MONEY_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_MONEY_2
     *
     * @param BUSI_MONEY_2 the value for PLT_COMMON_LOG.BUSI_MONEY_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_MONEY_2(BigDecimal BUSI_MONEY_2) {
        this.BUSI_MONEY_2 = BUSI_MONEY_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_1
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_1() {
        return BUSI_ITEM_1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_1
     *
     * @param BUSI_ITEM_1 the value for PLT_COMMON_LOG.BUSI_ITEM_1
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_1(String BUSI_ITEM_1) {
        this.BUSI_ITEM_1 = BUSI_ITEM_1 == null ? null : BUSI_ITEM_1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_2
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_2() {
        return BUSI_ITEM_2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_2
     *
     * @param BUSI_ITEM_2 the value for PLT_COMMON_LOG.BUSI_ITEM_2
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_2(String BUSI_ITEM_2) {
        this.BUSI_ITEM_2 = BUSI_ITEM_2 == null ? null : BUSI_ITEM_2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_3
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_3
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_3() {
        return BUSI_ITEM_3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_3
     *
     * @param BUSI_ITEM_3 the value for PLT_COMMON_LOG.BUSI_ITEM_3
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_3(String BUSI_ITEM_3) {
        this.BUSI_ITEM_3 = BUSI_ITEM_3 == null ? null : BUSI_ITEM_3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_4
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_4
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_4() {
        return BUSI_ITEM_4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_4
     *
     * @param BUSI_ITEM_4 the value for PLT_COMMON_LOG.BUSI_ITEM_4
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_4(String BUSI_ITEM_4) {
        this.BUSI_ITEM_4 = BUSI_ITEM_4 == null ? null : BUSI_ITEM_4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_5
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_5
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_5() {
        return BUSI_ITEM_5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_5
     *
     * @param BUSI_ITEM_5 the value for PLT_COMMON_LOG.BUSI_ITEM_5
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_5(String BUSI_ITEM_5) {
        this.BUSI_ITEM_5 = BUSI_ITEM_5 == null ? null : BUSI_ITEM_5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_6
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_6
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_6() {
        return BUSI_ITEM_6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_6
     *
     * @param BUSI_ITEM_6 the value for PLT_COMMON_LOG.BUSI_ITEM_6
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_6(String BUSI_ITEM_6) {
        this.BUSI_ITEM_6 = BUSI_ITEM_6 == null ? null : BUSI_ITEM_6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_7
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_7
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_7() {
        return BUSI_ITEM_7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_7
     *
     * @param BUSI_ITEM_7 the value for PLT_COMMON_LOG.BUSI_ITEM_7
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_7(String BUSI_ITEM_7) {
        this.BUSI_ITEM_7 = BUSI_ITEM_7 == null ? null : BUSI_ITEM_7.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_8
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_8
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_8() {
        return BUSI_ITEM_8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_8
     *
     * @param BUSI_ITEM_8 the value for PLT_COMMON_LOG.BUSI_ITEM_8
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_8(String BUSI_ITEM_8) {
        this.BUSI_ITEM_8 = BUSI_ITEM_8 == null ? null : BUSI_ITEM_8.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_9
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_9
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_9() {
        return BUSI_ITEM_9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_9
     *
     * @param BUSI_ITEM_9 the value for PLT_COMMON_LOG.BUSI_ITEM_9
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_9(String BUSI_ITEM_9) {
        this.BUSI_ITEM_9 = BUSI_ITEM_9 == null ? null : BUSI_ITEM_9.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_10
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_10
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_10() {
        return BUSI_ITEM_10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_10
     *
     * @param BUSI_ITEM_10 the value for PLT_COMMON_LOG.BUSI_ITEM_10
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_10(String BUSI_ITEM_10) {
        this.BUSI_ITEM_10 = BUSI_ITEM_10 == null ? null : BUSI_ITEM_10.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_11
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_11
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_11() {
        return BUSI_ITEM_11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_11
     *
     * @param BUSI_ITEM_11 the value for PLT_COMMON_LOG.BUSI_ITEM_11
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_11(String BUSI_ITEM_11) {
        this.BUSI_ITEM_11 = BUSI_ITEM_11 == null ? null : BUSI_ITEM_11.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_12
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_12
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_12() {
        return BUSI_ITEM_12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_12
     *
     * @param BUSI_ITEM_12 the value for PLT_COMMON_LOG.BUSI_ITEM_12
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_12(String BUSI_ITEM_12) {
        this.BUSI_ITEM_12 = BUSI_ITEM_12 == null ? null : BUSI_ITEM_12.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_13
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_13
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_13() {
        return BUSI_ITEM_13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_13
     *
     * @param BUSI_ITEM_13 the value for PLT_COMMON_LOG.BUSI_ITEM_13
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_13(String BUSI_ITEM_13) {
        this.BUSI_ITEM_13 = BUSI_ITEM_13 == null ? null : BUSI_ITEM_13.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_14
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_14
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_14() {
        return BUSI_ITEM_14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_14
     *
     * @param BUSI_ITEM_14 the value for PLT_COMMON_LOG.BUSI_ITEM_14
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_14(String BUSI_ITEM_14) {
        this.BUSI_ITEM_14 = BUSI_ITEM_14 == null ? null : BUSI_ITEM_14.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_COMMON_LOG.BUSI_ITEM_15
     *
     * @return the value of PLT_COMMON_LOG.BUSI_ITEM_15
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public String getBUSI_ITEM_15() {
        return BUSI_ITEM_15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_COMMON_LOG.BUSI_ITEM_15
     *
     * @param BUSI_ITEM_15 the value for PLT_COMMON_LOG.BUSI_ITEM_15
     *
     * @mbggenerated Sun Dec 04 15:31:02 CST 2016
     */
    public void setBUSI_ITEM_15(String BUSI_ITEM_15) {
        this.BUSI_ITEM_15 = BUSI_ITEM_15 == null ? null : BUSI_ITEM_15.trim();
    }
    
    @Override
	public String toString() {
		return "PltCommonLog [ID=" + ID + ", SERIAL_ID=" + SERIAL_ID + ", TENANT_ID=" + TENANT_ID + ", LOG_TYPE="
				+ LOG_TYPE + ", SPONSOR=" + SPONSOR + ", YYMMDD=" + YYMMDD + ", START_TIME=" + START_TIME
				+ ", END_TIME=" + END_TIME + ", DURATION=" + DURATION + ", BUSI_CODE=" + BUSI_CODE + ", DEST_NUM="
				+ DEST_NUM + ", BUSI_DESC=" + BUSI_DESC + ", BUSI_NUM_1=" + BUSI_NUM_1 + ", BUSI_NUM_2=" + BUSI_NUM_2
				+ ", BUSI_TIME_1=" + BUSI_TIME_1 + ", BUSI_TIME_2=" + BUSI_TIME_2 + ", BUSI_MONEY_1=" + BUSI_MONEY_1
				+ ", BUSI_MONEY_2=" + BUSI_MONEY_2 + ", BUSI_ITEM_1=" + BUSI_ITEM_1 + ", BUSI_ITEM_2=" + BUSI_ITEM_2
				+ ", BUSI_ITEM_3=" + BUSI_ITEM_3 + ", BUSI_ITEM_4=" + BUSI_ITEM_4 + ", BUSI_ITEM_5=" + BUSI_ITEM_5
				+ ", BUSI_ITEM_6=" + BUSI_ITEM_6 + ", BUSI_ITEM_7=" + BUSI_ITEM_7 + ", BUSI_ITEM_8=" + BUSI_ITEM_8
				+ ", BUSI_ITEM_9=" + BUSI_ITEM_9 + ", BUSI_ITEM_10=" + BUSI_ITEM_10 + ", BUSI_ITEM_11=" + BUSI_ITEM_11
				+ ", BUSI_ITEM_12=" + BUSI_ITEM_12 + ", BUSI_ITEM_13=" + BUSI_ITEM_13 + ", BUSI_ITEM_14=" + BUSI_ITEM_14
				+ ", BUSI_ITEM_15=" + BUSI_ITEM_15 + "]";
	}

	public PltCommonLog(){
    	
    }
    
    /**
     * @Title:PltCommonLog
     * @Description:the constructor of init with arguments
     * @author: LiJinfeng   
     * @date: 2017年3月3日 上午10:16:39
     * @param SERIAL_ID
     * @param TENANT_ID
     * @param LOG_TYPE
     * @param SPONSOR
     * @param activityId
     * @param activitySeqId
     */
    public PltCommonLog(Integer SERIAL_ID,String TENANT_ID,
    		String LOG_TYPE,String SPONSOR,String activityId,String activitySeqId){
    	
    	this.SERIAL_ID = SERIAL_ID;
    	this.TENANT_ID = TENANT_ID;
    	this.LOG_TYPE = LOG_TYPE;
    	this.SPONSOR = SPONSOR;
    	this.BUSI_ITEM_14 = activityId;
    	this.BUSI_ITEM_15 = activitySeqId;
    	
    }
    
    /**
     * @Title: cleanFields
     * @Description: set null to BUSI_ITEM_3-BUSI_ITEM_15
     * @return: void
     * @throws: 
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
	public void cleanFields(){
    	
    	try {
			Class clazz = PltCommonLog.class;
			for (int i = 1; i < 14; i++) {

				String methodName = "setBUSI_ITEM_";
				methodName = methodName + String.valueOf(i);
				Method setBUSI_ITEM = clazz.getMethod(methodName, new Class[] { String.class });
				Object[] arguments = new Object[] { null };
				setBUSI_ITEM.invoke(this, arguments);

			} 
			this.BUSI_CODE = null;
			this.BUSI_DESC = null;
			this.START_TIME = null;
			this.YYMMDD = null;
		} catch (Exception e) {
			log.info("occured exception when set fields for pltCommonLog");
			e.printStackTrace();
		}
    	
    }
    
    /**
     * @Title: setFields
     * @Description: set fields of pltCommonLog
     * @return: void
     * @param logMessage
     * @param parameters
     * @throws Exception
     * @throws: 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
	public void setFields(String logMessage,String logLevel,String... parameters){
    	
    	try {
			if (parameters.length > 12) {
				parameters = Arrays.copyOfRange(parameters, 0, 13);
				/*System.out.println(Arrays.deepToString(parameters));*/
			}
			this.BUSI_CODE = logLevel;
			this.BUSI_DESC = logMessage;
			Class clazz = PltCommonLog.class;
			/*Object object = clazz.newInstance();*/
			Date date = new Date();
			int i = 1;
			for (String parameter : parameters) {
                if(i==1&&parameter.length()>6000){
                	parameter = parameter.substring(0, 6000);
                }
                if(i==2&&parameter.length()>2048){
                	parameter = parameter.substring(0, 2048);
                }
                if(i>2&&parameter.length()>128){
                	parameter = parameter.substring(0, 128);
                }
				String methodName = "setBUSI_ITEM_";
				methodName = methodName + String.valueOf(i);
				Method setBUSI_ITEM = clazz.getMethod(methodName, new Class[] { String.class });
				Object[] arguments = new Object[] { parameter };
				setBUSI_ITEM.invoke(this, arguments);
				i++;

			}
			this.START_TIME = date;
			this.YYMMDD = Integer.parseInt(TimeUtil.date2String(date, "yyyyMMdd"));
		} catch (Exception e) {
			log.info("occured exception when set fields for pltCommonLog");
			e.printStackTrace();
		}   	
    	
    }
    
    @SuppressWarnings({ "unchecked", "rawtypes" })
	public void testLog(){
    	
    	try {
			Class clazz = log.getClass();
			/*Object object = clazz.newInstance();*/
			Method logType = clazz.getMethod("info", new Class[] { Object.class });
			Object[] arguments = new Object[] { "infoTest" };
		    logType.invoke(log, arguments);
		} catch (Exception e) {
			e.printStackTrace();
		}
    	
    }
    
    public static void main(String[] args) {
		
    	/*PltCommonLog pltCommonLog = new PltCommonLog();
        String logMessage = "test";
        String logLevel= "info";
        pltCommonLog.setFields(logMessage, logLevel,"3","4","5","6");
        System.out.println(pltCommonLog.toString());
        pltCommonLog.cleanFields();
        System.out.println(pltCommonLog.toString());*/
    	
    	/*PltCommonLog pltCommonLog = new PltCommonLog();
    	pltCommonLog.testLog();*/
    	
    	String s = "qwerrtttt";
    	s=s.substring(0, 6);
    	System.out.println(s.length());
        
	}
}