package com.bonc.busi.outer.model;

import java.io.Serializable;
import java.util.Date;

public class PltActivityChannelDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.REC_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private Integer REC_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.CHANN_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String CHANN_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.ACTIVITY_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String ACTIVITY_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.IS_SEND_SMS
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String IS_SEND_SMS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_CON
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String FILTER_CON;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_SQL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String FILTER_SQL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.TOUCHLIMITDAY
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String TOUCHLIMITDAY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.MARKET_WORDS
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String MARKET_WORDS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.SMS_WORDS
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String SMS_WORDS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.ORDERISSUEDRULE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String ORDERISSUEDRULE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.SPECIALTYPE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String SPECIALTYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.TENANT_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String TENANT_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.VAILDATE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String VAILDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.NUMBERLIMIT
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String NUMBERLIMIT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.TARGET
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String TARGET;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.TITLE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String TITLE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.CONTENT
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String CONTENT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.URL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String URL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.SEND_LEVEL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String SEND_LEVEL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.NOSEND_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String NOSEND_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.START_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private Date START_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.END_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private Date END_TIME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.TIMES
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private Integer TIMES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.INTERVAL_HOUR
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private Integer INTERVAL_HOUR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.MODEL_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String MODEL_ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.IMAGE_URL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String IMAGE_URL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.TYPE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String TYPE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.PRODUCT_LIST
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String PRODUCT_LIST;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.IMGSIZE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private Integer IMGSIZE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE1
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String RESERVE1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE2
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String RESERVE2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE3
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String RESERVE3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLT_ACTIVITY_CHANNEL_DETAIL.BUSINESS_HALL_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    private String BUSINESS_HALL_NAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.REC_ID
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.REC_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public Integer getREC_ID() {
        return REC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.REC_ID
     *
     * @param REC_ID the value for PLT_ACTIVITY_CHANNEL_DETAIL.REC_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setREC_ID(Integer REC_ID) {
        this.REC_ID = REC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.CHANN_ID
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.CHANN_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getCHANN_ID() {
        return CHANN_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.CHANN_ID
     *
     * @param CHANN_ID the value for PLT_ACTIVITY_CHANNEL_DETAIL.CHANN_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setCHANN_ID(String CHANN_ID) {
        this.CHANN_ID = CHANN_ID == null ? null : CHANN_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.ACTIVITY_ID
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.ACTIVITY_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getACTIVITY_ID() {
        return ACTIVITY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.ACTIVITY_ID
     *
     * @param ACTIVITY_ID the value for PLT_ACTIVITY_CHANNEL_DETAIL.ACTIVITY_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setACTIVITY_ID(String ACTIVITY_ID) {
        this.ACTIVITY_ID = ACTIVITY_ID == null ? null : ACTIVITY_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.IS_SEND_SMS
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.IS_SEND_SMS
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getIS_SEND_SMS() {
        return IS_SEND_SMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.IS_SEND_SMS
     *
     * @param IS_SEND_SMS the value for PLT_ACTIVITY_CHANNEL_DETAIL.IS_SEND_SMS
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setIS_SEND_SMS(String IS_SEND_SMS) {
        this.IS_SEND_SMS = IS_SEND_SMS == null ? null : IS_SEND_SMS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_CON
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_CON
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getFILTER_CON() {
        return FILTER_CON;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_CON
     *
     * @param FILTER_CON the value for PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_CON
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setFILTER_CON(String FILTER_CON) {
        this.FILTER_CON = FILTER_CON == null ? null : FILTER_CON.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_SQL
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_SQL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getFILTER_SQL() {
        return FILTER_SQL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_SQL
     *
     * @param FILTER_SQL the value for PLT_ACTIVITY_CHANNEL_DETAIL.FILTER_SQL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setFILTER_SQL(String FILTER_SQL) {
        this.FILTER_SQL = FILTER_SQL == null ? null : FILTER_SQL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TOUCHLIMITDAY
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.TOUCHLIMITDAY
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getTOUCHLIMITDAY() {
        return TOUCHLIMITDAY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TOUCHLIMITDAY
     *
     * @param TOUCHLIMITDAY the value for PLT_ACTIVITY_CHANNEL_DETAIL.TOUCHLIMITDAY
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setTOUCHLIMITDAY(String TOUCHLIMITDAY) {
        this.TOUCHLIMITDAY = TOUCHLIMITDAY == null ? null : TOUCHLIMITDAY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.MARKET_WORDS
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.MARKET_WORDS
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getMARKET_WORDS() {
        return MARKET_WORDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.MARKET_WORDS
     *
     * @param MARKET_WORDS the value for PLT_ACTIVITY_CHANNEL_DETAIL.MARKET_WORDS
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setMARKET_WORDS(String MARKET_WORDS) {
        this.MARKET_WORDS = MARKET_WORDS == null ? null : MARKET_WORDS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.SMS_WORDS
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.SMS_WORDS
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getSMS_WORDS() {
        return SMS_WORDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.SMS_WORDS
     *
     * @param SMS_WORDS the value for PLT_ACTIVITY_CHANNEL_DETAIL.SMS_WORDS
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setSMS_WORDS(String SMS_WORDS) {
        this.SMS_WORDS = SMS_WORDS == null ? null : SMS_WORDS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.ORDERISSUEDRULE
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.ORDERISSUEDRULE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getORDERISSUEDRULE() {
        return ORDERISSUEDRULE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.ORDERISSUEDRULE
     *
     * @param ORDERISSUEDRULE the value for PLT_ACTIVITY_CHANNEL_DETAIL.ORDERISSUEDRULE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setORDERISSUEDRULE(String ORDERISSUEDRULE) {
        this.ORDERISSUEDRULE = ORDERISSUEDRULE == null ? null : ORDERISSUEDRULE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.SPECIALTYPE
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.SPECIALTYPE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getSPECIALTYPE() {
        return SPECIALTYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.SPECIALTYPE
     *
     * @param SPECIALTYPE the value for PLT_ACTIVITY_CHANNEL_DETAIL.SPECIALTYPE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setSPECIALTYPE(String SPECIALTYPE) {
        this.SPECIALTYPE = SPECIALTYPE == null ? null : SPECIALTYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TENANT_ID
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.TENANT_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getTENANT_ID() {
        return TENANT_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TENANT_ID
     *
     * @param TENANT_ID the value for PLT_ACTIVITY_CHANNEL_DETAIL.TENANT_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setTENANT_ID(String TENANT_ID) {
        this.TENANT_ID = TENANT_ID == null ? null : TENANT_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.VAILDATE
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.VAILDATE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getVAILDATE() {
        return VAILDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.VAILDATE
     *
     * @param VAILDATE the value for PLT_ACTIVITY_CHANNEL_DETAIL.VAILDATE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setVAILDATE(String VAILDATE) {
        this.VAILDATE = VAILDATE == null ? null : VAILDATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.NUMBERLIMIT
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.NUMBERLIMIT
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getNUMBERLIMIT() {
        return NUMBERLIMIT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.NUMBERLIMIT
     *
     * @param NUMBERLIMIT the value for PLT_ACTIVITY_CHANNEL_DETAIL.NUMBERLIMIT
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setNUMBERLIMIT(String NUMBERLIMIT) {
        this.NUMBERLIMIT = NUMBERLIMIT == null ? null : NUMBERLIMIT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TARGET
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.TARGET
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getTARGET() {
        return TARGET;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TARGET
     *
     * @param TARGET the value for PLT_ACTIVITY_CHANNEL_DETAIL.TARGET
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setTARGET(String TARGET) {
        this.TARGET = TARGET == null ? null : TARGET.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TITLE
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.TITLE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getTITLE() {
        return TITLE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TITLE
     *
     * @param TITLE the value for PLT_ACTIVITY_CHANNEL_DETAIL.TITLE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setTITLE(String TITLE) {
        this.TITLE = TITLE == null ? null : TITLE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.CONTENT
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.CONTENT
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getCONTENT() {
        return CONTENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.CONTENT
     *
     * @param CONTENT the value for PLT_ACTIVITY_CHANNEL_DETAIL.CONTENT
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setCONTENT(String CONTENT) {
        this.CONTENT = CONTENT == null ? null : CONTENT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.URL
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.URL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getURL() {
        return URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.URL
     *
     * @param URL the value for PLT_ACTIVITY_CHANNEL_DETAIL.URL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setURL(String URL) {
        this.URL = URL == null ? null : URL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.SEND_LEVEL
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.SEND_LEVEL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getSEND_LEVEL() {
        return SEND_LEVEL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.SEND_LEVEL
     *
     * @param SEND_LEVEL the value for PLT_ACTIVITY_CHANNEL_DETAIL.SEND_LEVEL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setSEND_LEVEL(String SEND_LEVEL) {
        this.SEND_LEVEL = SEND_LEVEL == null ? null : SEND_LEVEL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.NOSEND_TIME
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.NOSEND_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getNOSEND_TIME() {
        return NOSEND_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.NOSEND_TIME
     *
     * @param NOSEND_TIME the value for PLT_ACTIVITY_CHANNEL_DETAIL.NOSEND_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setNOSEND_TIME(String NOSEND_TIME) {
        this.NOSEND_TIME = NOSEND_TIME == null ? null : NOSEND_TIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.START_TIME
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.START_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public Date getSTART_TIME() {
        return START_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.START_TIME
     *
     * @param START_TIME the value for PLT_ACTIVITY_CHANNEL_DETAIL.START_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setSTART_TIME(Date START_TIME) {
        this.START_TIME = START_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.END_TIME
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.END_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public Date getEND_TIME() {
        return END_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.END_TIME
     *
     * @param END_TIME the value for PLT_ACTIVITY_CHANNEL_DETAIL.END_TIME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setEND_TIME(Date END_TIME) {
        this.END_TIME = END_TIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TIMES
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.TIMES
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public Integer getTIMES() {
        return TIMES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TIMES
     *
     * @param TIMES the value for PLT_ACTIVITY_CHANNEL_DETAIL.TIMES
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setTIMES(Integer TIMES) {
        this.TIMES = TIMES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.INTERVAL_HOUR
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.INTERVAL_HOUR
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public Integer getINTERVAL_HOUR() {
        return INTERVAL_HOUR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.INTERVAL_HOUR
     *
     * @param INTERVAL_HOUR the value for PLT_ACTIVITY_CHANNEL_DETAIL.INTERVAL_HOUR
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setINTERVAL_HOUR(Integer INTERVAL_HOUR) {
        this.INTERVAL_HOUR = INTERVAL_HOUR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.MODEL_ID
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.MODEL_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getMODEL_ID() {
        return MODEL_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.MODEL_ID
     *
     * @param MODEL_ID the value for PLT_ACTIVITY_CHANNEL_DETAIL.MODEL_ID
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setMODEL_ID(String MODEL_ID) {
        this.MODEL_ID = MODEL_ID == null ? null : MODEL_ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.IMAGE_URL
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.IMAGE_URL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getIMAGE_URL() {
        return IMAGE_URL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.IMAGE_URL
     *
     * @param IMAGE_URL the value for PLT_ACTIVITY_CHANNEL_DETAIL.IMAGE_URL
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setIMAGE_URL(String IMAGE_URL) {
        this.IMAGE_URL = IMAGE_URL == null ? null : IMAGE_URL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TYPE
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.TYPE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.TYPE
     *
     * @param TYPE the value for PLT_ACTIVITY_CHANNEL_DETAIL.TYPE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setTYPE(String TYPE) {
        this.TYPE = TYPE == null ? null : TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.PRODUCT_LIST
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.PRODUCT_LIST
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getPRODUCT_LIST() {
        return PRODUCT_LIST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.PRODUCT_LIST
     *
     * @param PRODUCT_LIST the value for PLT_ACTIVITY_CHANNEL_DETAIL.PRODUCT_LIST
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setPRODUCT_LIST(String PRODUCT_LIST) {
        this.PRODUCT_LIST = PRODUCT_LIST == null ? null : PRODUCT_LIST.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.IMGSIZE
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.IMGSIZE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public Integer getIMGSIZE() {
        return IMGSIZE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.IMGSIZE
     *
     * @param IMGSIZE the value for PLT_ACTIVITY_CHANNEL_DETAIL.IMGSIZE
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setIMGSIZE(Integer IMGSIZE) {
        this.IMGSIZE = IMGSIZE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE1
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE1
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getRESERVE1() {
        return RESERVE1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE1
     *
     * @param RESERVE1 the value for PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE1
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setRESERVE1(String RESERVE1) {
        this.RESERVE1 = RESERVE1 == null ? null : RESERVE1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE2
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE2
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getRESERVE2() {
        return RESERVE2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE2
     *
     * @param RESERVE2 the value for PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE2
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setRESERVE2(String RESERVE2) {
        this.RESERVE2 = RESERVE2 == null ? null : RESERVE2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE3
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE3
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getRESERVE3() {
        return RESERVE3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE3
     *
     * @param RESERVE3 the value for PLT_ACTIVITY_CHANNEL_DETAIL.RESERVE3
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setRESERVE3(String RESERVE3) {
        this.RESERVE3 = RESERVE3 == null ? null : RESERVE3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.BUSINESS_HALL_NAME
     *
     * @return the value of PLT_ACTIVITY_CHANNEL_DETAIL.BUSINESS_HALL_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public String getBUSINESS_HALL_NAME() {
        return BUSINESS_HALL_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLT_ACTIVITY_CHANNEL_DETAIL.BUSINESS_HALL_NAME
     *
     * @param BUSINESS_HALL_NAME the value for PLT_ACTIVITY_CHANNEL_DETAIL.BUSINESS_HALL_NAME
     *
     * @mbggenerated Mon Dec 05 17:01:37 CST 2016
     */
    public void setBUSINESS_HALL_NAME(String BUSINESS_HALL_NAME) {
        this.BUSINESS_HALL_NAME = BUSINESS_HALL_NAME == null ? null : BUSINESS_HALL_NAME.trim();
    }
}