FROM 192.168.0.29:5000/tomcat:7-jre7-ths
COPY target/ordertask-service.war /usr/local/tomcat/webapps/
RUN mv /usr/local/tomcat/webapps/ordertask-service.war /usr/local/tomcat/webapps/ordertask-service.war
CMD ["catalina.sh", "run"]

